artifacts_root: artifacts

data_ingeston:
    root_dir: artifacts/data_ingestion
    source_url: https://github.com/neelakandanoj/Wine-Quality-E2E/raw/main/Wine_dataset.zip
    local_data_file: artifacts/data_ingestion/data.zip
    unzip_dir: artifacts/data_ingestion